version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8000:8000"

  message_service:
    build:
      context: ./message_service
    ports:
      - "8001:8001"
    depends_on:
      - user_service 

  like_service:
    build:
      context: ./like_service
    ports:
      - "8002:8002"
    depends_on:
      - user_service
      - message_service
